# Screen Reader Math

*A bit about screen readers with math support.*

## NVDA

NVDA from NV Access is a popular screen reader on Windows, and it has robust math support! As of the 2026 stable release, MathCAT support is built-in!

### Features for speech:

  - navigate math horizontally and vertically
  - announce math customization:
     - no announcement
     - annoounce with beep (sound a beep before and after each math expression)
  - switch between 3 spoken math engines
  - change verbosity level
  - copy as MathML, LaTeX, AsciiMath
  - above features supported for MathML in HTML, PDF, and EPUB

### Mathjax vs MathML + Mathjax

*Performance comparison of NVDA on HTML files with "only Mathjax" versus MathML and Mathjax.*

Mathjax provide amazing accessibility features for people who don't rely on speech output of screen readers. However, the default options used in popular implementations can degrade screen reader performance. For example, if every math expression is announced with "clickable," this defeats the purpose of being able to change math announcement between **none**  and **announce with beep**.

For this reason, it is important to be mindful of how Mathjax is incorporated into HTML files. If possible, it is best to use a tool that writes math as MathML into the HTML file. This way the user can readily use the file offline, get the best accessibility outputs, and choose between using Mathjax and not using it (opening it offline).
