# Accessible Math

{{construction}}

## Accessible Outputs Via Mathpix

You can use the following routes to create accessible outputs via Mathpix:

- DOCX | export as Word document
- HTML \ | export as HTML, after enabling export with MathML in settings
- PDF \ \ \ | export to Overleaf, and add the tagpdf invocation; compile to PDF

Or, you can use Markdown results from Mathpix to output multiple formats (PDF, HTML, EPUB, Word) at once.

Mathpix snipping tool can OCR:

- individual math equations/expressions
- paragraphs containing numbers as currency, simple math, lists
  - useful when you need correct unicode characters for simple math
- tables
- lists
- chemical equations

Mathpix can also convert entire documents.

## Creating Accessible Math PDFs

In my opinion, the best way to create accessible math PDFs is via LaTeX, using the tagdf package.

I prefer doing this through R Markdown, but if you are using straight LaTeX, one convenient way is combining Mathpix and Overleaf.

*Currently, Mathpix does not directly export PDFs with accessible math—neither the option **PDF (with HTML)** or **PDF (with LaTeX)** exports accessible math PDFs. (Testing; Mathpix support, personal communication 07/24/2026).*

Introduction to LaTeX

: The best guide to LaTeX is [Overleaf](https://www.overleaf.com/learn).

Overleaf supports TeX Live 2025, which means you can use the tagpdf package in it! Additionally, Mathpix integrates directly with Overleaf, so you can upload a PDF, export it to Overleaf, and add in the tagpdf invocation to output an accessible PDF.

A basic LaTeX file (example name: filename.tex) looks like this:

```latex
\documentclass{article}
\begin{document}
\section{Heading 1}
Some text goes here.
\end{document}
```

This file can then be converted to a PDF with the appropriate software (examples: TeX Live, MiKTeX, and TinyTeX). Historically, the \\documentclass{} declaration in the "preamble" has been the first line in a LaTeX file. However, with the creation of the tagpdf package (added to allow for the creation of accessible PDFs via LaTeX), there's a new first line on the scene: \\DocumentMetadata{}! Instead of including tagpdf in the preamble with a "\\usepackage{}" declaration, you include tagpdf by putting in the \\DocumentMetadata{} line at the very top:


```latex
DocumentMetadata()
\documentclass{article}
\begin{document}
\section{Heading 1}
Some text goes here.
\end{document}
```

If you want to compile this to accessible PDF with local software, you'll need a full TeX Live (minimum version 2025) to do so. However, you can also do so in your browser with Overleaf, which is what we'll use for the demonstration.

<!--
:

::: {.figure-row}

iframe

:::
-->

You might think you have to be a LaTeX aficionado to write up your LaTeX documents, but actually . . . Mathpix can do this for you! There is an "export to Overleaf" option that lets you export PDFs you OCR with Mathpix straight into Overleaf.

<!--
Let's take a look:

::::: {.figure-row}

::: {.figure}
iframe
[If Overleaf doesn't open automatically, make sure to allow popups from the site in your browser.]{.figcaption}
:::

:::::

This will output a PDF with the math incorporated as both structure elements and as Associated Files.

\pictureofaccessible.

The following is the text of the speech viewer for NVDA when it reads from the PDF:

> lorem

Video Demonstration:

-->
## Screen Reader Math

*A bit about screen readers with math support.*

### NVDA

NVDA from NV Access is a popular screen reader on Windows, and it has robust math support! As of the 2026 stable release, MathCAT support is built-in!

#### Features for speech:

  - navigate math horizontally and vertically
  - announce math customization:
     - no announcement
     - announce with beep (sound a beep before and after each math expression)
  - switch between 3 spoken math engines
  - change verbosity level
  - copy as MathML, LaTeX, AsciiMath
  - above features supported for MathML in HTML, PDF, and EPUB

#### Mathjax vs MathML + Mathjax

*Performance comparison of NVDA on HTML files with "only Mathjax" versus MathML and Mathjax.*

Mathjax provide amazing accessibility features for people who don't rely on speech output of screen readers. However, the default options used in popular implementations can degrade screen reader performance. For example, if every math expression is announced with "clickable," this defeats the purpose of being able to change math announcement between **none**  and **announce with beep**.

For this reason, it is important to be mindful of how Mathjax is incorporated into HTML files. If possible, it is best to use a tool that writes math as MathML into the HTML file. This way the user can readily use the file offline, get the best accessibility outputs, and choose between using Mathjax and not using it (opening it offline).

## Spoken Math

A number of different spoken math engines exist, each designed to prioritize different principles: ease of use (without training), explicitness, precision. Examples are MathSpeak, Clear Speak, LiteralSpeak, SimpleSpeak.

- MathSpeak can be particularly useful for post-secondary math. A company called See.Write.Hear developed it from the [mathspeak](https://accessinghigherground.org/handouts2013/HTCTU%20Alt%20Format%20Manuals/Math%20Accommodations/07%20MATHSPEAK.pdf) system created by Dr. Abraham Nemeth, the creator of the Nemeth Math Braille Code. 

  ::: {.det}
  [Learn More]{.summ}
  
  If you want to learn more about accessible math, or about digital accessibility in general, I recommend reading the 
  full lecture above. However, here are some highlights.
  
  In it, Nemeth discusses the system that he and his readers (students he hired) used for pronouncing and transcribing mathematical texts. (This was not a formalized spoken math engine, but was later developed into one by a company.)
  
  This quote highlights the nature (literal, explicit, verbose/wordy) of his system.
  
  > Lowercase letters are pronounced at face value without modification. They are never combined to form words. In particular, the trigonometric and other function abbreviations are spelled out rather than pronounced as words. We say "s i n" rather than "sine," "t a n" rather than "tan" or "tangent," "l o g" rather than "log," etc.” . . . A single uppercase letter is spoken as "upper" followed by the name of the letter. If a word is in uppercase, it is spoken as "upword" followed by the sequence of letters in the word, pronounced one letter at a time.
  
  However, the part of this lecture that I find the most illuminating for someone new to math accessibility is the discussion of fractions. In it, he illustrates how some information that is immediately available to sighted readers can be incorporated into a system for math pronunciation in a way that is concise. This is important, as he explains, so that an unsighted reader has access to the same information as a sighted reader at the same time in the cognitive process of reading:
  
  >We say "B-frac" as an abbreviation for "begin-fraction," and "E-frac" as an abbreviation for "end-fraction". We say "over" for the fraction line. . . . 
>
>A simple fraction (which has no subsidiary fractions) is said to be of order 0. By induction, a fraction of order n has at least one subsidiary fraction of order n-1. A fraction of order 1 is frequently referred to as a complex fraction, and one of order 2 as a hypercomplex fraction. Complex fractions are fairly common, hypercomplex fractions are rare, and fractions of higher order are practically non-existent. The order of a fraction is readily determined by a simple visual inspection, so that the sighted reader forms an immediate mental orientation to the nature of the notation with which he is dealing. It is important for a Braille reader to have this same information at the same time that it is available to the sighted reader. Without this information, the Braille reader may discover that he is dealing with a fraction whose order is higher than he expected, and may have to reformulate his thinking accordingly long after he has become aware of the outer fraction.
>
To communicate the presence of a complex fraction, we say "B-B-frac," "O-over," and"E-E-frac" for the components of a complex fraction . . . For a hypercomplex fraction, the components are spoken as "B-B-B-frac," "O-O-over," and "E-E-E-frac," respectively. You can see that the speech patterns are designed to facilitate transcription in the Nemeth Code, according to the rules of that Code.


  :::
