# Meta

This is a Bookdown GitBook site hosted on GitHub pages. With [GitHub Flow](https://docs.github.com/en/get-started/using-github/github-flow), it serves as a wiki. However, I won't be accepting contributions until I have completed more of the site construction.

## Syntax {-}

:::{.det}
[Collapsible Section]{.summ}

- syntax:

  ```
  :::{.det}
  [A Summary]{.summ}
  
  Details Go Here
  
  #. Item 1
  #. Item 2
  #. Item 3
  
  :::
  ```

- produces:

  :::{.det}
  
  [A Summary]{.summ}
  
  Details Go Here
  
  #. Item 1
  #. Item 2
  #. Item 3
  
  :::

:::

:::{.det}

[Page Construction Label]{.summ}

- syntax: 

  ```
  {{construction}}
  ```
- produces:

  {{construction}}

:::


:::{.det}

[Section Construction Label]{.summ}

- syntax:

  ```
  {{sconstruction}}
  ```

- produces:

  {{sconstruction}}

:::


:::{.det}

[Page-Specific TOC]{.summ}


- syntax:

  ```
  :::{.back-toc}

  [TOC](#page-specific-toc-label)
  
  :::
  ```
- produces:

  *(uses example toc-link)*

  :::{.back-toc}

  [TOC](#bs-toc)
  
  :::

:::

:::{.det}

[Footnote Labels]{.summ}

To separate out footnote labels across different pages, I append an abbreviation for each page to the number. For example, a footnote on the W*ord* R*emediation* page might get the label `[^wr_1]` rather than `[^1]`.

:::

## Link Labels

[msnip]: https://snip.mathpix.com/home  "Mathpix Snip Web App"

- `[msnip]: https://snip.mathpix.com/home  "Mathpix Snip Web App"`

## Maintenance

*The syntax above is achieved at times through "hacks" (in the sense of being poorly constructed), so the below should not be reused.*

- macro-filter.lua
- style.css

## Style Guide

| Use |
|:---:|
| lorem ipsum Mathpix |
| lorem ipsum Overleaf |
| lorem ipsum Markdown |
| lorem ipsum Pandoc |
| lorem ipsum GitHub |
| lorem ipsum VS Code|
| lorem ipsum R Markdown |
| lorem ipsum Bookdown |
| lorem ipsum LaTeX |
| lorem ipsum TeX |
| lorem ipsum Jupyter Notebook | 
| lorem ipsum Adobe Acrobat Pro|
| lorem ipsum Adobe Acrobat Reader |
| lorem ipsum OneDrive |
| lorem ipsum TeX Live |
| lorem ipsum MiKTeX |
| lorem ipsum alt text |
| lorem ipsum alternative text[^m_1] |
| lorem ipsum endnote |
| lorem ipsum **Clickable Button Name** |
| lorem ipsum *Non-clickable UI Component Name * |
| lorem ipsum **Ctrl** + **Alt** + **Right Arrow** |
| lorem ipsum **Ctrl** + **A** |
| drop-down menu |

### Video Style Guide

:::{.det}

[Guidelines for elements of video demonstrations.]{.summ}

- Use dark theme when possible.
- Don't use Windows high-contrast themes.
- Black mouse with white outline.
- Enlarge mouse.
- Learning objectives at beginning.
- List tools to be used.
- Outline parts of video after learning objectives.
- Summary of learning at end.
- Time-lapse repetitive periods.
  - Show once at full-speed.
  - Use an icon to indicate time-lapse.
- Zoom inset when actions are too small to view.
  - Visible outline on insets.
- Outline key buttons and tabs.
  - Preference to purple and green.
- Prefer black-and-white designs (accessibility).

:::

[^m_1]: As opposed to *alternate text*.
